### ISSUE TITLE
Locale Foutmelding

### ISSUE THREAD

**Issue by rduivenvoorde** [opengeogroep/ruimtelijkeplannen#10]
Bij het installeren van de plugin bij de provincie Zeeland, in een verse QGIS kreeg ik de volgende melding.
Wanneer ik expliciet in de settings aangaf: system locale negeren en dan op NL zetten ging het wel goed....

Kon plug-in 'RuimtelijkePlannen' niet laden wegens een fout bij het aanroepen van de methode classFactory() 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/testwin10/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RuimtelijkePlannen\__init__.py", line 35, in classFactory
    return RuimtelijkePlannen(iface)
  File "C:/Users/testwin10/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RuimtelijkePlannen\ruimtelijke_plannen.py", line 165, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

Python versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS versie: 3.4.7-Madeira Madeira, 5c56989325 

Python pad:

**Comment by MarcoDuiker** [comment]
hmm, dat stukje code wordt volgens mij gegenereerd door de plugin builder plugin.

In master zou het nu gefixed moeten zijn. Wil jij dat proberen, want ik krijg jou probleem niet gereproduceerd?

Indien ok, zal ik een nieuwe release samenstellen.

**Comment by rduivenvoorde** [comment]
Het vervelende is dat ik het niet meer kan reproduceren nu hier.
Het was een versie windows machine met een schone QGIS erop, en blijkbaar heeft tie nu die setting gemaakt, of in de environment opgenomen.

Ook als ik alle profielen weggooi, krijg ik met
QSettings().value('locale/userLocale')[0:2]
altijd netjes 'nl' terug...

Wat ik wel kan reproduceren is:

QSettings().value('locale/globalLocale')[0:2]
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
TypeError: 'NoneType' object is not subscriptable
QSettings().value('locale/globalLocale')

Maar ik denk dus dat je test uit master zal werken want onderstaande geeft netjes True terug:
not QSettings().value('locale/globalLocale')
True

Ik meen me te herinneren dat ik 'NULL' terugkreeg vanochtend.

Misschien zelfs van maken:

if not QSettings().value('locale/userLocale') and QSettings().value('locale/globalLocale') is not None:
  locale = QSettings().value('locale/globalLocale')[0:2]
elif QSettings().value('locale/userLocale')[0:2] is not None:
  locale = QSettings().value('locale/userLocale')[0:2]
else:
  locale = 'nl'

Of is dat te?

**Comment by raymondnijssen** [comment]
@rduivenvoorde Volgens mij krijgen mijn cursisten diezelfde foutmelding ook wel eens na installatie van de pdok plugin. En die werken natuurlijk ook vaak met een verse qgis installatie op windows. Ik heb dan nooit tijd om er echt in te duiken,maar het is vaker voorgekomen. Volgende x maak ik een foto van hun scherm
