### ISSUE TITLE
plan type BPB

### ISSUE THREAD

**Issue by CPWE** [opengeogroep/ruimtelijkeplannen#12]
krijg foutmelding bij selecteren NL.IMRO.0119.TFGNoordpoort-BPB1. Type wordt niet ondersteund ?

**Comment by MarcoDuiker** [comment]
De plugin werkt nu alleen voor plannen op het tabblad "JURIDISCH". Dit betreft het tabblad zoals de bestond in de "oude" ruimtelijke plannen viewer.

In de "nieuwe" ruimtelijke plannen viewer is de opzet met tabbladen vervangen door de keuzehulp, en is daarmee niet meer zo duidelijk welke plansoorten wel, en welke plansoorten niet door de plugin worden ondersteund. 

De foutmelding geeft wel netjes aan wat er gebeurd. Dit plantype wordt niet ondersteund. (Het betreft een plan dat in de ontwerpfase zit.)

Uiteraard zouden we graag willen dat we meer plantypen kunnen ondersteunen. Pull requests of een geldelijke ondersteuning zijn welkom.

**Comment by MarcoDuiker** [comment]
Gefixed in 3.3.0.
Deze versie wordt na testen doorgezet naar de QGIS plugins repo.
