### ISSUE TITLE
Warning: Invalid layer

### ISSUE THREAD

**Issue by martijnvg123** [opengeogroep/ruimtelijkeplannen#13]
When loading in a zoning plan into QGIS, I get the error: "Warning: Invalid layer ...." for each layer. After the warning it doesn't load anything, it only creates the group with the zoning plan identification.

**Comment by martijnvg123** [comment]
![image](https://user-images.githubusercontent.com/60513838/73549164-5bfc1980-4442-11ea-8fa5-aa080088ce7d.png)

**Comment by MarcoDuiker** [comment]
All zoning plans, or this specific one?

**Comment by martijnvg123** [comment]
I've tried multiple plan, with no success.

**Comment by martijnvg123** [comment]
Also, I've tried it too on a colleague's PC, with the same error.

**Comment by MarcoDuiker** [comment]
The message log panel reveals that the ruimtelijkeplannen service is down. Nothing I can do about that.

We'll have to wait till it's up again.

![image](https://user-images.githubusercontent.com/28801402/73551465-b9926500-4446-11ea-9e04-3a85a1017d78.png)

**Comment by MarcoDuiker** [comment]
You might open an issue on geoforum.

**Comment by martijnvg123** [comment]
Thanks for letting me know! We'll try again on monday. If it's still down by then, I'll make a post on the geoforum.

**Comment by MarcoDuiker** [comment]
Better open an issue right away, so they know it is used. And can solve problems over the weekend, if they are severe.

**Comment by martijnvg123** [comment]
Done

**Comment by MarcoDuiker** [comment]
indeed it was a ruimtelijkeplannen service problem. Closing.
