### ISSUE TITLE
Plugin blijft hangen op locatie waar WFS geen content biedt

### ISSUE THREAD

**Issue by HansvanderMeij** [opengeogroep/ruimtelijkeplannen#14]
Op een locatie in gemeente Wijdemeren lijkt een (klein) ruimtelijk plan te ontbreken. Want ook de PDOK WMS bestemmingsplangebied geeft hier geen content. 
Als je deze locatie aanwijst, dan blijft de plugin hangen (wait-cursor).  Op zich kan je verder nog wel andere QGIS handelingen verrichten (gelukkig...).

Situatie:
![image](https://user-images.githubusercontent.com/24246044/81800545-47d0b980-9513-11ea-9f6b-fbaa6860166a.png)

Lijkt op een eerder issue...

**Comment by MarcoDuiker** [comment]
Ik kan me geen eerder issue herinneren wat hier op lijkt.

Anyhow, dit issue treedt inderdaad op wanneer de RP plannen service geen enkel plan beschikbaar heeft op een locatie. Dat zou eigenlijk niet voor moeten komen.
De waitcursor wordt dan niet netjes teruggezet.

Fixed in master.
