### ISSUE TITLE
QGIS plugin Ruimtelijke Plannen geeft foutmelding

### ISSUE THREAD

**Issue by pim-ict** [opengeogroep/ruimtelijkeplannen#16]
Sinds 2 juni is de betreffende service door RP afgeschermd voor externe requests:

RuimtelijkePlannen.network.networkaccessmanager.RequestsException: Network error #403: Error transferring https://www.ruimtelijkeplannen.nl/plannenservice/plannen/xy/206307.75002382422/459983.8472627246 - server replied: Forbidden

**Comment by MarcoDuiker** [comment]
Er wordt hard gewerkt aan een oplossing.

**Comment by MarcoDuiker** [comment]
Er is inmiddels een oplossing in versie 3.5.2. Zie ook: https://geoforum.nl/t/403-forbidden-op-https-www-ruimtelijkeplannen-nl-plannenservice-plannen/7292/8

**Comment by pim-ict** [comment]
Top Marco, Bedankt. Ook voor de referentie naar het geoforum..
Co
