### ISSUE TITLE
afnemers.ruimtelijkeplannen.nl/plannenservice/plannen off-line?

### ISSUE THREAD

**Issue by oosterhagen** [opengeogroep/ruimtelijkeplannen#18]
De plug-in kan niet bij bestanden op de server van het Kadaster:

Python foutmelding:
/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RuimtelijkePlannen\network\networkaccessmanager.py", line 267, in request
              raise self.http_call_result.exception
             RuimtelijkePlannen.network.networkaccessmanager.RequestsException: Network error #404: Error transferring https://afnemers.ruimtelijkeplannen.nl/plannenservice/plannen/xy/.... - server replied: Not Found

**Comment by MarcoDuiker** [comment]
De servoce van afnemers.ruimtelijkeplannen.nl is down.
Daar kunnen wij als plugin makers niet zoveel aan doen.

Melden op Geoforum is zinniger.

**Comment by MarcoDuiker** [comment]
De boel is weer gefixed.
