### ISSUE TITLE
De Plugin ruimtelijke plannen op Qgis werk niet. Ik heb op twee pc's met twee versies van Qgis getest. Beiden geven dezelfde melding.

### ISSUE THREAD

**Issue by MasselinkD** [opengeogroep/ruimtelijkeplannen#19]
Er is een fout opgetreden bij het uitvoeren van Python code: 

RuimtelijkePlannen.network.networkaccessmanager.RequestsException: Network error #404: Error transferring https://afnemers.ruimtelijkeplannen.nl/plannenservice/plannen/identificatie/NL.IMRO.0153.BP00116-0003 - server replied: Not Found 
Traceback (most recent call last):
  File "C:\Users/Dennis Masselink/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RuimtelijkePlannen\ruimtelijke_plannen.py", line 540, in addRPplanFromToolbar
    self.addFromIdn(self.toolbarSearch.text())
  File "C:\Users/Dennis Masselink/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RuimtelijkePlannen\ruimtelijke_plannen.py", line 548, in addFromIdn
    (response, content) = self.nam.request(url, headers = self.rp_search_headers)
  File "C:\Users/Dennis Masselink/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RuimtelijkePlannen\network\networkaccessmanager.py", line 267, in request
    raise self.http_call_result.exception
RuimtelijkePlannen.network.networkaccessmanager.RequestsException: Network error #404: Error transferring https://afnemers.ruimtelijkeplannen.nl/plannenservice/plannen/identificatie/NL.IMRO.0153.BP00116-0003 - server replied: Not Found

Python versie: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS versie: 3.34.0-Prizren Prizren, ffbdd67881 

Python pad:
C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python
C:/Users/Dennis Masselink/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Dennis Masselink/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.0\apps\grass\grass83\etc\python
C:\Users\Dennis Masselink\Documents
C:\Program Files\QGIS 3.34.0\bin\python39.zip
C:\PROGRA~1\QGIS33~1.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib
C:\Program Files\QGIS 3.34.0\bin
C:\PROGRA~1\QGIS33~1.0\apps\Python39
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Dennis Masselink/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by MarcoDuiker** [comment]
De services van ruimtelijke plannen.nl lijken down. Zie: https://geoforum.nl/t/afnemers-service-ruimtelijke-plannen-down/8916

**Comment by MarcoDuiker** [comment]
De boel is weer gefixed.
