### ISSUE TITLE
QGis 3.0 Support

### ISSUE THREAD

**Issue by jkroon-dadvies** [opengeogroep/ruimtelijkeplannen#8]
Are there any plans to create a QGis 3 supported version of this plugin? The plugin works fine in QGis 2.

**Comment by raymondnijssen** [comment]
No plans so far

**Comment by MarcoDuiker** [comment]
Yes, we are working on it.

**Comment by jkroon-dadvies** [comment]
Nice to hear,

Let me know if I could test something.

**Comment by MarcoDuiker** [comment]
There is a first release candidate available for testing at: https://github.com/opengeogroep/ruimtelijkeplannen/blob/master/releases/RuimtelijkePlannen-3.2-RC1.zip

**Comment by jkroon-dadvies** [comment]
When adding the wrong string in the RuimtelijkePlannen Bar it gives a Python error:
Traceback (most recent call last):
              File "/AppData/Roaming/QGIS/QGIS3\profiles\PDOK/python/plugins\RuimtelijkePlannen\ruimtelijke_plannen.py", line 343, in addRPplanFromToolbar
              self.addFromIdn(self.toolbarSearch.text())
              File "/AppData/Roaming/QGIS/QGIS3\profiles\PDOK/python/plugins\RuimtelijkePlannen\ruimtelijke_plannen.py", line 360, in addFromIdn
              level = Qgis.Critical)
             NameError: name 'Qgis' is not defined

I think the plugin is trying to create a Critical message to the user but the Qgis class is not present at that point.

**Comment by MarcoDuiker** [comment]
Thank you.
Fixed in the new release candidate: https://github.com/opengeogroep/ruimtelijkeplannen/blob/master/releases/RuimtelijkePlannen-3.2-RC2.zip

**Comment by raymondnijssen** [comment]
Now available in the QGIS plugin repository. Thank you @MarcoDuiker !
